name: munge
version: git
summary: Munge authentication service.
description: |
  MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for creating and validating credentials. 

grade: stable
confinement: strict

base: core18

slots:
  munged-socket:
    interface: content
    content: socket-directory
    write: 
      - $SNAP_DATA

apps:
  munged:
    daemon: simple
    command: wrappers/munged
    slots:
      - munged-socket
    plugs:
      - network
      - network-bind

  munge:
    command: wrappers/munge

  unmunge:
    command: wrappers/unmunge

  remunged:
    command: wrappers/remunge

parts:
  munge:
    plugin: dump
    source: https://github.com/dun/munge.git
    source-type: git
    source-depth: 1
    source-branch: master
    build-packages:
      - gcc
      - libssl-dev
      - autoconf
      - make
      - libtool
      - zlib1g-dev
      - libbz2-dev
    stage:
      - usr/
      - var/
      - etc/
    prime:
      - usr/
      - etc/
      - var/
    override-build: |
      snapcraftctl build
      ./bootstrap
      ./configure --prefix=$SNAPCRAFT_PART_INSTALL/usr \
          --sysconfdir=$SNAPCRAFT_PART_INSTALL/etc \
          --localstatedir=$SNAPCRAFT_PART_INSTALL/var \
          --libdir=$SNAPCRAFT_PART_INSTALL/usr/lib/x86_64-linux-gnu
      make
      make install

  wrappers:
    plugin: dump
    source: wrap/
