#!/bin/bash

set -eux

################################### Create Munge Dirs ###################################
# This directory contains the daemon's secret key. The recommended permissions for it are 0700.
mkdir -p $SNAP_COMMON/etc/munge
chmod -R 0700 $SNAP_COMMON/etc/munge

# This directory contains the daemon's PRNG seed file. It is also where the daemon
# creates pipes for authenticating clients via file-descriptor-passing. If the
# file-descriptor-passing authentication method is being used, this directory must
# allow execute permissions for all; however, it should not expose read permissions.
# The recommended permissions for it are 0711.
mkdir -p $SNAP_COMMON/var/lib/munge
chmod -R 0711 $SNAP_COMMON/var/lib/munge

# This directory contains the daemon's log file. The recommended permissions for it are 0700.
mkdir -p $SNAP_COMMON/var/log/munge
chmod -R 0700 $SNAP_COMMON/var/log/munge

# This directory contains the Unix domain socket for clients to communicate with the daemon.
# It also contains the daemon's pid file. This directory must allow execute permissions for all.
# The recommended permissions for it are 0755.
mkdir -p $SNAP_COMMON/var/run/munge
chmod -R 0755 $SNAP_COMMON/var/run/munge

exit 0
